{"uuid": "89ccdfec-fe91-4fdd-a3df-1d72b8a2ffd0", "children": ["2e48665e-0f59-41b3-af31-d32aa704e94f"], "befores": [{"name": "run_app", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"C:\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = next(it)\n  File \"E:\\PycharmProjects\\app_automation_sh\\test_cases\\conftest.py\", line 47, in run_app\n  File \"E:\\PycharmProjects\\app_automation_sh\\test_cases\\conftest.py\", line 81, in _base_driver\n"}, "start": 1578669133772, "stop": 1578669133836}], "start": 1578669133772, "stop": 1578669133844}