{"uuid": "909b3105-1171-4058-b457-f4a502b4fea9", "children": ["9a6a5a0b-f958-414b-80ee-cff1a872146d"], "befores": [{"name": "run_app", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"C:\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = next(it)\n  File \"E:\\PycharmProjects\\app_automation_sh\\test_cases\\conftest.py\", line 47, in run_app\n  File \"E:\\PycharmProjects\\app_automation_sh\\test_cases\\conftest.py\", line 81, in _base_driver\n"}, "start": 1578669139922, "stop": 1578669139983}], "start": 1578669139922, "stop": 1578669139993}