{"uuid": "8f1242a0-6e9f-44ff-8a3d-15798fe8aaa2", "children": ["59a1d4be-aef1-49c4-8c04-fed77a8e87a6"], "befores": [{"name": "run_app", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"C:\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = next(it)\n  File \"E:\\PycharmProjects\\app_automation_sh\\test_cases\\conftest.py\", line 47, in run_app\n  File \"E:\\PycharmProjects\\app_automation_sh\\test_cases\\conftest.py\", line 81, in _base_driver\n"}, "start": 1578669139226, "stop": 1578669139279}], "start": 1578669139226, "stop": 1578669139287}