{"uuid": "fff8c43f-1c18-4769-89ae-d4879e59ba75", "children": ["0e6a673b-7f5a-4c3d-9599-4541c1def024"], "befores": [{"name": "run_app", "status": "broken", "statusDetails": {"message": "RuntimeError: No active exception to reraise\n", "trace": "  File \"C:\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 923, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 779, in call_fixture_func\n    res = next(it)\n  File \"E:\\PycharmProjects\\app_automation_sh\\test_cases\\conftest.py\", line 47, in run_app\n  File \"E:\\PycharmProjects\\app_automation_sh\\test_cases\\conftest.py\", line 81, in _base_driver\n"}, "start": 1578669138696, "stop": 1578669138756}], "start": 1578669138696, "stop": 1578669138764}